.PHONY: check check6 check7 check8 checkA

check: check6 check7 check8 checkA

check6:

check7: 
	sml test7.sml < /dev/null
	celf figure-7.1.clf
	celf figure-7.2.clf
	celf section-7.1-a.clf
	celf figure-7.4.clf
	celf section-7.1-b.clf
	celf section-7.1-c.clf
	celf figure-7.5-7.9.clf
	celf figure-7.11.clf

check8:

checkA: