.PHONY: check check6 check7 check8 checkA

check: check6 check7 check8 checkA

check6:
	sml test6.sml < /dev/null
	celf figure-6.1-a.clf
	celf figure-6.1-b.clf
	celf figure-6.2.clf
	celf section-6.1-a.clf
	celf figure-6.3.clf
	celf figure-6.4-a.clf
	celf figure-6.4-a.clf
	celf figure-6.5.clf
	celf figure-6.6.clf
	celf section-6.2-a.clf
	celf figure-6.8-a.clf
	celf figure-6.8-b.clf
	celf section-6.4-a.clf
	celf section-6.5-b.clf
	celf figure-6.9-a.clf
	celf figure-6.9-b.clf
	celf figure-6.10.clf
	celf figure-6.11.clf
	celf figure-6.12.clf
	celf figure-6.13.clf
	celf figure-6.14.clf
	celf figure-6.16.clf
	celf figure-6.17.clf
	celf figure-6.18.clf
	celf figure-6.19.clf
	celf figure-6.20.clf
	celf section-6.5-a.clf
	celf section-6.5-b.clf
	celf figure-6.21.clf
	celf figure-6.22.clf
	celf figure-6.23.clf
	celf section-6.6-a.clf
	celf figure-6.23.clf
	celf figure-6.24.clf
	celf section-6.6-b.clf
	celf figure-6.25.clf
	celf section-6.6-c.clf
	celf section-6.6-d.clf
	celf figure-6.26-6.27-a.clf
	celf figure-6.27-b.clf

check7: 
	sml test7.sml < /dev/null
	celf figure-7.1.clf
	celf figure-7.2.clf
	celf section-7.1-a.clf
	celf figure-7.4.clf
	celf section-7.1-b.clf
	celf section-7.1-c.clf
	celf figure-7.5-7.9.clf
	celf figure-7.11.clf

check8:
	sml test8.sml < /dev/null
	celf figure-8.1.clf
	celf section-8.2-a.clf
	celf section-8.2-b.clf
	celf figure-8.2.clf
	celf figure-8.3.clf
	celf figure-8.4.clf
	celf figure-8.5.clf
	celf figure-8.7-8.8.clf
	celf figure-8.9.clf

checkA:
	sml testA.sml < /dev/null